
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4000"
    depends_on:
      - backend
    volumes:
      - .:/workspace
      - /workspace/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/workspace
      - /workspace/node_modules

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Haru2023@@
      POSTGRES_DB: miniblog
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init-db:/docker-entrypoint-initdb.d
      - ./backend/upload:/workspace/upload
volumes:
  pgdata: